apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: discord-provider
  namespace: flux-system
spec:
  type: discord
  channel: flux
  secretRef:
    name: discord-url