apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: discord-url
    namespace: alerts
data:
    address: ENC[AES256_GCM,data:z3w4+wWmFGHyDyGshhkqmxxT6q6nLVIBcBT28zdj81f8gM50TavzvRvK1KsBaSprYuX7RWQUmV3IP2WWbTAzbQe2CC3UTiCMCVQe4qw6e9sGTPJzP69zaKZ9Me6aXF3yzHbMowhKs4AlG2TG+4EqWv/BiA4EEPdV++6u+C4HkVPvc86jNy880p2ztCIvBknrPN8dH0IOSBuFH1Jl9I2KJYHnf+8=,iv:+tS5wOn9RCOtC79ST6iWjnOPleYBl5rlnLMk5gyVWj4=,tag:18subt6DjnhC1pP53bf9YQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-14T22:33:57Z"
    mac: ENC[AES256_GCM,data:jB2GZBARGeOnxllhTTLpGDTv59JMfUTGmn9Z3Bem25SCeywZhU9E+pre8kJybFJ4q15iHxzQIGcul3RCH+XY89ujxlZ/X01n8GuIKcsUgmEV3pDyk4CZJINLHO53udMC/RgPOnnCK1C8485mR60IJblro7tssKjBWCd8uge6Eqg=,iv:XAwmDohewiVuwgZLW6WpTXraw2dX3wuigLH/O8L/nY4=,tag:QZYc4IcJXVmnbxCFA/kXCA==,type:str]
    pgp:
        - created_at: "2022-08-14T22:33:57Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxmLL2MdvkOfARAAnSLdpZ57n1SGN3sru92WLUaKJIyBSztEWq99gTxHuNLc
            VWO5K5CwVK+YFwk8o2It+l0/fhwP0mmhPa9YDwpveSNHLU6p4Mtu/jtt4OK36jYh
            4IkqDlwg6um1d3xNntv4XWB6cgQxphcm0SPQ1nnptNiohaVKFYEGCzAG/UhWMglR
            3mcUDEq8/0TYwm0HKk/T3gN0VIpaUoAwSOuSYCSv2oRb4t9BG+eF7XFVu0VjSoQ9
            3B88mSIzgjF/GZdXYKb48gyCkoa/phdHUXj9BBy8xjOMLDeq/AXccjjCDaKfktIU
            e8zxozeV7guZ3SYT7/WmA2LX1q+vc1JbNiP4lu+V7RSXopKDxoxTgZcfpNS32ff0
            yJp53HzRpvWu6mjh4eonjHtUykD9pUlUdEpwBpKvEycEvEVOENeeWm4WLS2FnzEi
            nkx/3OQfoL5ZgP4uY0peQsnq5Kqx9k/JtqnEOVrweRyrrV5Mh2RYAxOfS8GiM+rM
            wp5qc6uFRVQJNAIOfQVAwI/GCQXXeGYx1ItODjx6EjwBBQRi7RuLcAXf9vPOZ1xS
            kzGTa9llPZfIj8slJrsl4qqkHFjK/24d1Vqlmdc8JVnMMAPEHzFiNlrKAZXNvzpA
            bXe8T0n1mW2w47MEMzHHoEIg01FEAHWclSopbMltBVRYdBLu+Q/oE5S8ObgkaJbS
            XAE7lg0GQpCaY9H2vnR9mqsl+GAIgzfvPe41ZsMSlkiCYZJyGCqv1ACsXBiBnmza
            cis3F2ifYp02wgOd4Aao0jK1Dx8H8zgfYoQFRogHGnJR+dIo7ZiszBD/CGSX
            =RJQB
            -----END PGP MESSAGE-----
          fp: 5422FF44D67530D4FEFFF94D7324DA8A2FF7A7FE
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
