apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: discord
  namespace: alerts
spec:
  channel: flux
  secretRef:
    name: discord-url
  type: discord
  username: flux-alerts

