apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: discord-url
    namespace: alerts
data:
    address: ENC[AES256_GCM,data:QRMNN+/4ppwaWTASN+3kHq7ZVM6eM9zg8hIQLmfxwV1xi9bMx5nB7xoztxSjI8vkE1JGmmEQqz3q4VWzXh5/VGnRTgUEaFAjVs1OsmkmX3YWNoOoWnhoY5sQobw3moYP1YQExzf4wjD7Pb5G8zoesdBRZXoAABB7J1Xk2OygkbSx8oXfy7GqVgtbpdubCGLhPL76335fFUmq2c1Pdu9hVNGuN08=,iv:D28xd18F2rsd0/FSh8CFbz664GYxZpn8gvYAKT1Vsu8=,tag:leRE3hqarcr7a3r5Ru+fIw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-14T22:40:47Z"
    mac: ENC[AES256_GCM,data:NY9xnJysHcb+NcsscQOHM6NlvAHe4+4M8/TIE5p3a5rHtxKXGQYcOovtYa3Wfr+AxRlYN9TvSjAGmBDNWrIHN+OmmlRIJeDy0p7k9TcODhhgp5Bg+nClTzvJmrlpKDlsbhXwZStJaLQU5cgd3Z8ZVRuZsDU0odNT8G+rwnr2260=,iv:cQ0eKlwm8Y/rfULKV7z6LaCK3eUgehR6R/8tLhaP9Rg=,tag:ZqnvykgXaRltj2CXaT5lAA==,type:str]
    pgp:
        - created_at: "2022-08-14T22:40:47Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxmLL2MdvkOfAQ/+JI5LoNhyGO25Mh4ATmWPeKFN7V21Oa+Z5E3Q8PHjmpTF
            FVxcHFYHNTs+vhukTkFgH/5vdXD7RHs/EdYHLqBw+HcVIyfAZ0zFhpY+2e0T/jWz
            DCFBIsVUH5ZrmturA3gqxs05B21bOQ/5E3SFGvD5SPM8tgRqpMM9itp3p30von2I
            obVjWphMUrP9DNdMnwDh+LVqul5HhJGQMnLn/rqIif96CM94FAEMuF70UcR8AqhQ
            +gXu5iYkS4XZxh9fcBBFqx1Qu4XVfIqnGuN8W/sSAFvWUT43GRRcWbIU5NdLuMmD
            U03MFQvabJfUQguDAtlyGjY6VvEtLgwjGwdMfDgJU+LU0KyfkX3fXf735+s7nyPb
            ul+Roxmdn4VxMFDEo4aTOmJf6zTHS9i4Fjc+8MA9sjMNOK1sgSFsY1ab5oaw7PEh
            1tJNI5guTs+zGYpC4njsEMCvnSuYk0TV1b81nnVNIs96Hk8/4rOeQ9v5NDfd1e/I
            6MvzdBIeH32+5D4UgWY7RaovsDHQcjQJLqh5JZr3dGiROLp0hsXYfo1OCLSnvW5w
            3pjVzX0Etfkckz3Gjbas7/MekShoTc1xw3V8DCIDxG8m5lwaDb3xBT3oSsZH+32w
            1IFNTdYBA3Aw4Y65h1N2Pye3H7XeDaF+ViN53IIWfy9AfANZfnLbfhhRuh2WLYPS
            XgHoGmntGIrsRzf95phmIUJlTfjw25x4+qtmMtlunaoAi2b5ULW8Tek8KN47TRo5
            MWn6s7AmZooz6TYTAuPf8C0DVStvnDfV92epUG1EfO5ULnbSuAcpxENben75zF0=
            =+qzL
            -----END PGP MESSAGE-----
          fp: 5422FF44D67530D4FEFFF94D7324DA8A2FF7A7FE
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
