apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: discord-provider
  namespace: alerts
spec:
  type: discord
  channel: flux
  username: flux-alerts
  secretRef:
    name: discord-url