apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: kustomization-alert
  namespace: flux-system
spec:
  summary: "Kustomization failed for the desired new state"
  providerRef:
    name: discord-provider
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: '*'
      namespace: '*'
