apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: prometheus-community-artifact
  namespace: monitoring
spec:
  interval: 59m
  url: https://prometheus-community.github.io/helm-charts
