apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
  - helm-release.yaml
  - monitoring-config/
configMapGenerator:
  - name: chartmuseum-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
