apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flux-runners
  namespace: flux-runners
spec:
  interval: 5m
  chart:
    spec:
      chart: actions-runner
      sourceRef:
        kind: HelmRepository
        name: openshift-actions-runner
        namespace: flux-system
      version: "2"
  install:
    remediation:
      retries: 3
  values:
    namespace: flux-runners
    replicas: 3
    githubRepository: ""
    githubOwner: carrello-org
    ephemeral: true
    secretName: "github-pat"
    runnerGroup: "rpi-microk8s"
