apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flux-runners
  namespace: flux-runners
spec:
  interval: 5m
  chart:
    spec:
      chart: self-hosted-runners
      sourceRef:
        kind: HelmRepository
        name: chart-museum-registry
        namespace: chart-museum
      version: "0.1.0"
  install:
    remediation:
      retries: 3
  values:
    namespace: flux-runners
    replicas: 1
