apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: alerts
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./alerts
  prune: true
  wait: true
  timeout: 5m0s
  # Enable decryption
  decryption:
    # Use the SOPS provider
    provider: sops
    secretRef:
      name: sops-gpg
