apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: simple-backend-app
  namespace: simple-backend
spec:
  chart:
    spec:
      version: "0.1.0"
  values:
    resources: 
    limits:
      cpu: 10m
      memory: 24Mi
    requests:
      cpu: 10m
      memory: 24Mi
    microservicename: simplebackend2
    applicationNamespace: simple-backend
